"""make candidate_score experience and education nullable

Revision ID: 059bbb0f346b
Revises: ab794d7756c3
Create Date: 2026-08-28 14:12:05.915722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '059bbb0f346b'
down_revision: Union[str, None] = 'ab794d7756c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_scores', schema=None) as batch_op:
        batch_op.alter_column('experience_score',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('education_score',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate_scores', schema=None) as batch_op:
        batch_op.alter_column('education_score',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('experience_score',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
