"""create initial schema

Revision ID: 19c22957363d
Revises: 
Create Date: 2026-08-26 22:56:47.179485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19c22957363d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('resume_path', sa.String(length=500), nullable=False),
    sa.Column('resume_filename', sa.String(length=255), nullable=False),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('education', sa.String(length=200), nullable=True),
    sa.Column('education_level', sa.Integer(), nullable=True),
    sa.Column('experience_years', sa.Float(), nullable=True),
    sa.Column('projects', sa.JSON(), nullable=False),
    sa.Column('certifications', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=True),
    sa.Column('parse_status', sa.Enum('parsed', 'partial', 'parse_failed', name='parsestatus', native_enum=False, length=32), nullable=False),
    sa.Column('parse_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidates_email'), ['email'], unique=False)

    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('department', sa.String(length=80), nullable=False),
    sa.Column('job_level', sa.Integer(), nullable=False),
    sa.Column('monthly_income', sa.Float(), nullable=False),
    sa.Column('years_at_company', sa.Integer(), nullable=False),
    sa.Column('years_since_last_promotion', sa.Integer(), nullable=False),
    sa.Column('years_with_curr_manager', sa.Integer(), nullable=False),
    sa.Column('total_working_years', sa.Integer(), nullable=False),
    sa.Column('job_satisfaction', sa.Integer(), nullable=False),
    sa.Column('environment_satisfaction', sa.Integer(), nullable=False),
    sa.Column('relationship_satisfaction', sa.Integer(), nullable=False),
    sa.Column('performance_rating', sa.Integer(), nullable=False),
    sa.Column('overtime', sa.Boolean(), nullable=False),
    sa.Column('business_travel', sa.String(length=40), nullable=False),
    sa.Column('distance_from_home', sa.Integer(), nullable=False),
    sa.Column('percent_salary_hike', sa.Float(), nullable=False),
    sa.Column('stock_option_level', sa.Integer(), nullable=False),
    sa.Column('attrition', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('recruiter', 'manager', 'analyst', 'admin', name='userrole', native_enum=False, length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('attrition_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('low', 'medium', 'high', name='risklevel', native_enum=False, length=32), nullable=False),
    sa.Column('top_factors', sa.JSON(), nullable=False),
    sa.Column('model_version', sa.String(length=40), nullable=False),
    sa.Column('prediction_date', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attrition_predictions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attrition_predictions_employee_id'), ['employee_id'], unique=False)

    op.create_table('candidate_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('skill_name', sa.String(length=80), nullable=False),
    sa.Column('skill_type', sa.Enum('technical', 'tool', 'soft', 'domain', name='skilltype', native_enum=False, length=32), nullable=False),
    sa.Column('source', sa.Enum('dictionary', 'semantic', name='skillsource', native_enum=False, length=32), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'skill_name', name='uq_candidate_skills_candidate_skill')
    )
    with op.batch_alter_table('candidate_skills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_skills_candidate_id'), ['candidate_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required_skills', sa.JSON(), nullable=False),
    sa.Column('min_experience_years', sa.Float(), nullable=False),
    sa.Column('education_requirement', sa.String(length=80), nullable=False),
    sa.Column('seniority', sa.Enum('junior', 'mid', 'senior', 'lead', name='jobseniority', native_enum=False, length=32), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='jobstatus', native_enum=False, length=32), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_title'), ['title'], unique=False)

    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('new', 'shortlisted', 'interviewed', 'selected', 'rejected', name='applicationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_applications_candidate_job')
    )
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_applications_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_applications_job_id'), ['job_id'], unique=False)

    op.create_table('candidate_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resume_match_score', sa.Float(), nullable=False),
    sa.Column('skill_match_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('education_score', sa.Float(), nullable=False),
    sa.Column('final_fit_score', sa.Float(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('additional_skills', sa.JSON(), nullable=False),
    sa.Column('scoring_method', sa.Enum('tfidf', 'embedding', name='scoringmethod', native_enum=False, length=32), nullable=False),
    sa.Column('score_version', sa.Integer(), nullable=False),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'job_id', name='uq_candidate_scores_candidate_job')
    )
    with op.batch_alter_table('candidate_scores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_candidate_scores_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_scores_final_fit_score'), ['final_fit_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_candidate_scores_job_id'), ['job_id'], unique=False)

    op.create_table('interview_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('technical', 'project', 'experience', 'skill_verification', 'behavioral', name='questioncategory', native_enum=False, length=32), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='questiondifficulty', native_enum=False, length=32), nullable=False),
    sa.Column('rationale', sa.String(length=400), nullable=True),
    sa.Column('generation_batch', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_interview_questions_candidate_id'), ['candidate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_interview_questions_job_id'), ['job_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_interview_questions_job_id'))
        batch_op.drop_index(batch_op.f('ix_interview_questions_candidate_id'))

    op.drop_table('interview_questions')
    with op.batch_alter_table('candidate_scores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_scores_job_id'))
        batch_op.drop_index(batch_op.f('ix_candidate_scores_final_fit_score'))
        batch_op.drop_index(batch_op.f('ix_candidate_scores_candidate_id'))

    op.drop_table('candidate_scores')
    with op.batch_alter_table('applications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_applications_job_id'))
        batch_op.drop_index(batch_op.f('ix_applications_candidate_id'))

    op.drop_table('applications')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_title'))

    op.drop_table('jobs')
    with op.batch_alter_table('candidate_skills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidate_skills_candidate_id'))

    op.drop_table('candidate_skills')
    with op.batch_alter_table('attrition_predictions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attrition_predictions_employee_id'))

    op.drop_table('attrition_predictions')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('employees')
    with op.batch_alter_table('candidates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_candidates_email'))

    op.drop_table('candidates')
    # ### end Alembic commands ###
