"""add grounding filter counts to interview_questions

Revision ID: 35b61a4acce8
Revises: 059bbb0f346b
Create Date: 2026-08-29 23:00:11.367153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35b61a4acce8'
down_revision: Union[str, None] = '059bbb0f346b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('generated', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('grounded', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interview_questions', schema=None) as batch_op:
        batch_op.drop_column('grounded')
        batch_op.drop_column('generated')
        batch_op.drop_column('requested')

    # ### end Alembic commands ###
